# Generated by Django 5.2.7 on 2025-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_rename_notifications_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
