# Generated by Django 5.2.7 on 2025-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "New like"),
                    ("comment", "New comment"),
                    ("subscription", "New subscription"),
                ],
                max_length=30,
            ),
        ),
    ]
